# Basic environment for RadTraQ.
name: radtraq_env
channels:
  - conda-forge
  - defaults
dependencies:
  - act-atmos
  - numpy
  - scipy
  - xarray
  - matplotlib
  - netcdf4
  - pint
  - flake8
  - pytest
  - pytest-cov
  - pytest-mpl
  - coveralls
  - pip
