name: Python Package using Conda

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Cancel concurrent runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.os }}-${{ matrix.python-version }}
    if: github.repository == 'ARM-Development/RadTraQ'
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        os: [macOS, ubuntu, Windows]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Conda Environment
        uses: mamba-org/setup-micromamba@v2.0.4
        with:
          environment-file: ./continuous_integration/environment_actions.yml
          init-shell: >-
            bash
          cache-downloads: true
          post-cleanup: "all"
          create-args: python=${{ matrix.python-version }}

      - name: Fetch all history for all tags and branches
        run: |
          git fetch --prune --unshallow

      - name: Test with pytest
        run: |
          python -m pytest --mpl --cov=radtraq/
