name: RadTRAQ

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Cancel concurrent runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.os }}-${{ matrix.python-version }}
    if: github.repository == 'ARM-Development/RadTraQ'
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [macOS, ubuntu, Windows]
        inlcude:
          - os: macos-latest
            PLAT: arm64
            INTERFACE64: ""
            platform: [x64]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install libproj-dev proj-data proj-bin
        sudo apt-get install libgeos-dev
        pip install --upgrade cython numpy pyshp six configparser
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --max-line-length=115 --ignore=F401,E402,W504,W605,F403
    - name: Test with pytest
      run: |
        python setup.py install
        pip install pytest
        pytest
